### ISSUE TITLE
is_plugin_active_for_network is not available on init

### ISSUE THREAD

**Issue by phatsk** [WebDevStudios/WDS-WP-REST-API-Connect-UI#1]
The plugin fails during `check_requirements`:

> Fatal error: Call to undefined function is_plugin_active_for_network() in /srv/www/msdynamics/htdocs/wp-content/plugins/wds-rest-connect-ui/wds-rest-connect-ui.php on line 220

**Comment by jtsternberg** [comment]
Thanks
